{% set name = "shelephant" %}
{% set org = "tdegeus" %}
{% set version = "0.21.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 38ad93ad6523d10e128b5ec19cc8673c8407953f5f46839fa40446d99f880c62

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - shelephant = shelephant.cli:_shelephant_main
    - shelephant_cp = shelephant.cli:_shelephant_cp_main
    - shelephant_diff = shelephant.cli:_shelephant_diff_main
    - shelephant_dump = shelephant.cli:_shelephant_dump_main
    - shelephant_hostinfo = shelephant.cli:_shelephant_hostinfo_main
    - shelephant_mv = shelephant.cli:_shelephant_mv_main
    - shelephant_parse = shelephant.cli:_shelephant_parse_main
    - shelephant_rm = shelephant.cli:_shelephant_rm_main

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - click
    - numpy
    - prettytable
    - python >=3
    - pyyaml
    - tqdm

test:
  imports:
    - {{ name }}
  commands:
    - shelephant --version
    - shelephant_cp --version
    - shelephant_diff --version
    - shelephant_dump --version
    - shelephant_hostinfo --version
    - shelephant_mv --version
    - shelephant_parse --version
    - shelephant_rm --version
    - pip check
    - python -c "import {{ name }}; assert {{ name }}.version == '{{ version }}'"
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dataset management
  description: Dataset management
  doc_url: https://{{ name }}.readthedocs.io
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
